# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(default='NULL', max_length=200)),
                ('sender', models.CharField(default='NULL', max_length=200)),
                ('receiving_number', models.IntegerField(default=0)),
                ('receiving_name', models.CharField(default='NULL', max_length=200)),
                ('message', models.TextField(default='NULL', max_length=500)),
                ('url_link', models.URLField(default='NULL', max_length=1000)),
            ],
        ),
    ]
