# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textIt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='provider',
            field=models.CharField(choices=[('ATT', 'att'), ('SPRINT', 'sprint')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='message',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='receiving_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='receiving_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='recipient',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='url_link',
            field=models.URLField(max_length=1000),
        ),
    ]
