# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textIt', '0002_auto_20160907_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='recipient',
            name='provider',
            field=models.CharField(choices=[('TMOBILE', 'T-Mobile'), ('SPRINT', 'Sprint'), ('CRICKET', 'Cricket'), ('ATT', 'AT&T'), ('VERIZON', 'Verizon')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='receiving_number',
            field=models.CharField(max_length=20),
        ),
    ]
