# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textIt', '0004_auto_20160910_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='message',
            field=models.TextField(default='NULL', max_length=500),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='provider',
            field=models.CharField(choices=[('@vtext.com', 'Verizon'), ('@tmomail.net', 'T-Mobile'), ('@mms.mycricket.com', 'Cricket'), ('@txt.att.net', 'AT&T'), ('@pm.sprint.com', 'Sprint')], default='NULL', max_length=20),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='receiving_name',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='receiving_number',
            field=models.CharField(default='NULL', max_length=20),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='recipient',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='url_link',
            field=models.URLField(default='NULL', max_length=1000),
        ),
    ]
