# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textIt', '0005_auto_20160913_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='provider',
            field=models.CharField(choices=[('@txt.att.net', 'AT&T'), ('@pm.sprint.com', 'Sprint'), ('@mms.mycricket.com', 'Cricket'), ('@vtext.com', 'Verizon'), ('@tmomail.net', 'T-Mobile')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='receiving_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='url_link',
            field=models.URLField(max_length=1000),
        ),
    ]
