# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textIt', '0006_auto_20160913_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='message',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='provider',
            field=models.CharField(choices=[('@txt.att.net', 'AT&T'), ('@pm.sprint.com', 'Sprint'), ('@tmomail.net', 'T-Mobile'), ('@mms.cricketwireless.net', 'Cricket'), ('@vtext.com', 'Verizon')], max_length=20, null=True),
        ),
    ]
