# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textIt', '0007_auto_20160913_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='contact_message',
        ),
        migrations.AlterField(
            model_name='recipient',
            name='provider',
            field=models.CharField(choices=[('@pm.sprint.com', 'Sprint'), ('@vtext.com', 'Verizon'), ('@txt.att.net', 'AT&T'), ('@mms.cricketwireless.net', 'Cricket'), ('@tmomail.net', 'T-Mobile')], max_length=20, null=True),
        ),
    ]
