# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textIt', '0008_auto_20160913_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedUser', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=20)),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_provider', models.CharField(choices=[('@mms.cricketwireless.net', 'Cricket'), ('@vtext.com', 'Verizon'), ('@txt.att.net', 'AT&T'), ('@pm.sprint.com', 'Sprint'), ('@tmomail.net', 'T-Mobile')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='recipient',
            name='provider',
            field=models.CharField(choices=[('@mms.cricketwireless.net', 'Cricket'), ('@vtext.com', 'Verizon'), ('@txt.att.net', 'AT&T'), ('@pm.sprint.com', 'Sprint'), ('@tmomail.net', 'T-Mobile')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='receiving_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='url_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
